// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGjQeIhnlZ0C80b627_iATtiLnWynJ7sU',
    appId: '1:499009956911:web:d21e1739132a18fc412ada',
    messagingSenderId: '499009956911',
    projectId: 'job-application-d1d1',
    authDomain: 'job-application-d1d1.firebaseapp.com',
    storageBucket: 'job-application-d1d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9M0AQxxB2j9OifhFLN2usdPfl6R5p2TM',
    appId: '1:499009956911:android:4c604b8d404c3bb2412ada',
    messagingSenderId: '499009956911',
    projectId: 'job-application-d1d1',
    storageBucket: 'job-application-d1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_8EtKkIQrg1X9SszWwO0p_H3wzNeSKxE',
    appId: '1:499009956911:ios:ff05651801213763412ada',
    messagingSenderId: '499009956911',
    projectId: 'job-application-d1d1',
    storageBucket: 'job-application-d1d1.firebasestorage.app',
    iosBundleId: 'com.example.naxanTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_8EtKkIQrg1X9SszWwO0p_H3wzNeSKxE',
    appId: '1:499009956911:ios:ff05651801213763412ada',
    messagingSenderId: '499009956911',
    projectId: 'job-application-d1d1',
    storageBucket: 'job-application-d1d1.firebasestorage.app',
    iosBundleId: 'com.example.naxanTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGjQeIhnlZ0C80b627_iATtiLnWynJ7sU',
    appId: '1:499009956911:web:86f8680c78d13d4c412ada',
    messagingSenderId: '499009956911',
    projectId: 'job-application-d1d1',
    authDomain: 'job-application-d1d1.firebaseapp.com',
    storageBucket: 'job-application-d1d1.firebasestorage.app',
  );

}